FROM registry.centos.org/kbsingh/openshift-nginx:latest
MAINTAINER "Konrad Kleine <kkleine@redhat.com>"

ENV LANG=en_US.utf8

USER root
ADD nginx.conf /etc/nginx/nginx.conf


RUN rm -rf /usr/share/nginx/html/*

COPY dist /usr/share/nginx/html
RUN chmod -R 777 /usr/share/nginx/html/

USER 997
